import type { State } from "./types";

const today = new Date();
const iso = (d: Date) => d.toISOString();
const addDays = (n: number) => { const d = new Date(today); d.setDate(d.getDate() + n); return d; };

export const seed: State = {
  activeProjectId: "p-workos",
  projects: [
    { id: "p-workos", name: "WorkOS", description: "Sistema de control de tareas de Yego", leadIds: ["m-paola"] },
  ],
  areas: [
    { id: "a-admin",     name: "Administración",          color: "#ef4444" },
    { id: "a-flota",     name: "Flota",                   color: "#f97316" },
    { id: "a-gerencia",  name: "Gerencia",                color: "#eab308" },
    { id: "a-lealtad",   name: "Lealtad",                 color: "#a855f7" },
    { id: "a-marketing", name: "Marketing",               color: "#ec4899" },
    { id: "a-ops",       name: "Operaciones",             color: "#06b6d4" },
    { id: "a-fleet",     name: "Producto Fleet",          color: "#0ea5e9" },
    { id: "a-sac",       name: "SAC",                     color: "#22c55e" },
    { id: "a-sistemas",  name: "Sistemas",                color: "#14b8a6" },
    { id: "a-ti",        name: "Tecnología de la Información", color: "#6366f1" },
  ],
  members: [
    { id: "m-paola",  name: "Paola Dayana Jorge Chacón",  initials: "PD", role: "SUPERADMIN", area: "a-admin",   color: "#ef4444" },
    { id: "m-eduardo",name: "Eduardo Yober Huayanca",     initials: "EY", role: "MONITOR",    area: "a-flota",   color: "#f97316" },
    { id: "m-felipe", name: "Felipe Castillo",            initials: "FC", role: "ADMIN",      area: "a-flota",   color: "#0ea5e9" },
    { id: "m-juan",   name: "Juan Carlos Mamani",         initials: "JC", role: "MIEMBRO",    area: "a-flota",   color: "#22c55e" },
    { id: "m-mariana",name: "Mariana Aguirre",            initials: "MA", role: "MIEMBRO",    area: "a-flota",   color: "#a855f7" },
    { id: "m-alex",   name: "Alexandra Paola Tumpay",     initials: "AP", role: "LEALTAD",    area: "a-lealtad", color: "#ec4899" },
    { id: "m-carla",  name: "Carla Flores",               initials: "CF", role: "MIEMBRO",    area: "a-lealtad", color: "#14b8a6" },
    { id: "m-diego",  name: "Diego Fernández",            initials: "DF", role: "MIEMBRO",    area: "a-lealtad", color: "#6366f1" },
  ],
  sprints: [
    {
      id: "s-1", name: "Sprint 1 · Estabilización", goal: "Estabilizar flota y reducir incidencias en SAC un 30%.",
      projectId: "p-workos", status: "activo",
      startDate: iso(addDays(-3)), endDate: iso(addDays(11)),
      capacityPoints: 40, createdAt: iso(addDays(-10)),
    },
    {
      id: "s-2", name: "Sprint 2 · Lealtad Q2", goal: "Lanzar nueva campaña de lealtad y métricas de retención.",
      projectId: "p-workos", status: "planificacion",
      startDate: iso(addDays(12)), endDate: iso(addDays(26)),
      capacityPoints: 36, createdAt: iso(addDays(-2)),
    },
    {
      id: "s-0", name: "Sprint 0 · Kickoff", goal: "Setup inicial y descubrimiento.",
      projectId: "p-workos", status: "completado",
      startDate: iso(addDays(-24)), endDate: iso(addDays(-10)),
      capacityPoints: 28, createdAt: iso(addDays(-30)),
    },
  ],
  tasks: [
    { id: "t-1", title: "Auditar incidencias de flota", description: "Revisar tickets SAC últimos 30 días.",
      projectId: "p-workos", areaId: "a-flota", assigneeIds: ["m-felipe","m-juan"],
      status: "en_progreso", priority: "media", progress: 35,
      startDate: iso(addDays(-2)), endDate: iso(addDays(4)),
      storyPoints: 5, sprintId: "s-1", createdAt: iso(addDays(-3)) },
    { id: "t-2", title: "Plan de retención lealtad", description: "Diseñar matriz de beneficios.",
      projectId: "p-workos", areaId: "a-lealtad", assigneeIds: ["m-alex","m-carla"],
      status: "en_progreso", priority: "alta", progress: 60,
      startDate: iso(addDays(0)), endDate: iso(addDays(6)),
      storyPoints: 8, sprintId: "s-1", createdAt: iso(addDays(-4)) },
    { id: "t-3", title: "Migración módulo administración", description: "Reemplazar legacy admin.",
      projectId: "p-workos", areaId: "a-admin", assigneeIds: ["m-paola"],
      status: "en_riesgo", priority: "urgente", progress: 50,
      startDate: iso(addDays(-1)), endDate: iso(addDays(2)),
      storyPoints: 13, sprintId: "s-1", createdAt: iso(addDays(-6)) },
    { id: "t-4", title: "Programa fidelización tier oro", description: "Definir reglas y comunicaciones.",
      projectId: "p-workos", areaId: "a-lealtad", assigneeIds: ["m-alex","m-diego"],
      status: "pendiente", priority: "alta", progress: 0,
      startDate: iso(addDays(5)), endDate: iso(addDays(20)),
      storyPoints: 8, sprintId: "s-2", createdAt: iso(addDays(-1)) },
    { id: "t-5", title: "Refactor pipeline de despliegues", description: "Mejorar tiempos de build.",
      projectId: "p-workos", areaId: "a-sistemas", assigneeIds: ["m-eduardo"],
      status: "bloqueada", priority: "alta", progress: 20,
      startDate: iso(addDays(-1)), endDate: iso(addDays(8)),
      storyPoints: 5, sprintId: "s-1", createdAt: iso(addDays(-5)),
      blockedReason: "Esperando aprobación de presupuesto cloud" },
    { id: "t-6", title: "KPIs de operaciones Q2", description: "Construir dashboard ejecutivo.",
      projectId: "p-workos", areaId: "a-ops", assigneeIds: ["m-paola","m-eduardo"],
      status: "en_progreso", priority: "media", progress: 40,
      startDate: iso(addDays(2)), endDate: iso(addDays(10)),
      storyPoints: 5, sprintId: "s-1", createdAt: iso(addDays(-2)) },
    { id: "t-7", title: "Onboarding de monitores SAC", description: "Capacitación inicial.",
      projectId: "p-workos", areaId: "a-sac", assigneeIds: ["m-mariana"],
      status: "pendiente", priority: "baja", progress: 0,
      startDate: iso(addDays(8)), endDate: iso(addDays(14)),
      storyPoints: 3, sprintId: null, createdAt: iso(addDays(-1)) },
    { id: "t-8", title: "Investigación churn lealtad", description: "Encuesta + entrevistas.",
      projectId: "p-workos", areaId: "a-lealtad", assigneeIds: ["m-carla"],
      status: "completada", priority: "media", progress: 100,
      startDate: iso(addDays(-20)), endDate: iso(addDays(-12)),
      storyPoints: 5, sprintId: "s-0", createdAt: iso(addDays(-25)),
      completedAt: iso(addDays(-12)) },
    { id: "t-9", title: "Política de incentivos flota", description: "Bonos por cumplimiento.",
      projectId: "p-workos", areaId: "a-flota", assigneeIds: ["m-felipe"],
      status: "pendiente", priority: "media", progress: 0,
      startDate: iso(addDays(14)), endDate: iso(addDays(22)),
      storyPoints: 5, sprintId: "s-2", createdAt: iso(addDays(-1)) },
    { id: "t-10", title: "Marketing mes aniversario", description: "Plan de campaña 360.",
      projectId: "p-workos", areaId: "a-marketing", assigneeIds: ["m-diego","m-alex"],
      status: "pendiente", priority: "alta", progress: 0,
      startDate: iso(addDays(10)), endDate: iso(addDays(24)),
      storyPoints: 8, sprintId: null, createdAt: iso(addDays(-1)) },
    { id: "t-11", title: "Setup repos y CI", description: "Bootstrap de monorepo.",
      projectId: "p-workos", areaId: "a-sistemas", assigneeIds: ["m-eduardo"],
      status: "completada", priority: "alta", progress: 100,
      startDate: iso(addDays(-22)), endDate: iso(addDays(-15)),
      storyPoints: 8, sprintId: "s-0", createdAt: iso(addDays(-26)),
      completedAt: iso(addDays(-15)) },
    { id: "t-12", title: "Auditoría seguridad TI", description: "Pentest interno.",
      projectId: "p-workos", areaId: "a-ti", assigneeIds: ["m-paola"],
      status: "en_riesgo", priority: "urgente", progress: 25,
      startDate: iso(addDays(-1)), endDate: iso(addDays(5)),
      storyPoints: 13, sprintId: "s-1", createdAt: iso(addDays(-3)) },
  ],
};
